[package]
name = "rust-steam"
version = "0.2.0"
edition = "2021"
description = "A Rust implementation of the IAPWS-IF97 steam tables"
repository = "https://github.com/marciorvneto/rusteam"
license = "MIT"

[dependencies]
float-cmp = "0.10.0"

[lib]
name = "rust_steam"
path = "src/iapws97.rs"
